spring.application.name=spring-boot-ecommerce
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=<DB-URL>
spring.datasource.username=<DB-USERNAME>
spring.datasource.password=<DB-PASSWORD>

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.data.rest.base-path=/api

allowed.origins=https://localhost:4200

spring.data.rest.detection-strategy=annotated


okta.oauth2.client-id=<AUTH CLIENT-id>
okta.oauth2.issuer=<AUTH Domain>
okta.oauth2.audience=http://localhost:8080